### PR TITLE
Fix #4994

### LINKED ISSUE #4994: this was not captured for this lamda function
This issue tracker is only for technical issues related to Dash Core.

General Dash questions and/or support requests and are best directed to the [Dashpay Reddit](https://www.reddit.com/r/dashpay/).

To report critical security issues, email infosec@dash.org and/or see the DASH bug bounty program on [Bugcrowd](https://bugcrowd.com/dashdigitalcash) instead of creating Github issues.

### Describe the issue
  CXX      coinjoin/libdash_server_a-server.o
In file included from coinjoin/server.cpp:8:0:
./evo/deterministicmns.h: In lambda function:
./evo/deterministicmns.h:207:85: error: `this' was not captured for this lambda function
         return ranges::count_if(mnMap, [](const auto& p){ return IsMNValid(*p.second); });
                                                                                     ^

### Can you reliably reproduce the issue?
yess
#### If so, please list the steps to reproduce below:

cd dash/src/depends
make
cd ../
./authgen.sh
./configure --enable-glibc-back-compat --prefix=$(pwd)/depends/x86_64-pc-linux-gnu LDFLAGS="-static-libstdc++" --enable-cxx --enable-static --disable-shared --disable-debug --disable-tests --disable-bench --with-pic CPPFLAGS="-fPIC -O3 --param ggc-min-expand=1 --param ggc-min-heapsize=32768" CXXFLAGS="-fPIC -O3 --param ggc-min-expand=1 --param ggc-min-heapsize=32768"
make

### Expected behaviour
Tell us what should happen
should build clean
### Actual behaviour
Tell us what happens instead
error above

GCC version ubuntu 7.5.0

NOTE: it builds fine on ubuntu 20.04 with GCC version ubuntu 9.4.0
dash 17  master prior to this update built OK a couple of weeks ago.

### What version of Dash Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
75289fc - master branch
### Machine specs:
- OS: ubuntu 18.04
- CPU:dual xeon DL380 G7
- RAM:128G
- Disk size:2T
- Disk Type (HD/SDD): managed i410

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

### PR DESCRIPTION
**Pull request by thelazier**
Fix #4994 , error: `this' was not captured for this lambda function

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by UdjinM6** [comment]
superseded by #5468
