### PR TITLE
test: update evo snapshot v3 golden hash after MN shares DIP

### PR DESCRIPTION
**Pull request by UdjinM6**
## Issue being fixed or feature implemented

```
test/evo_snapshot_tests.cpp(319): error: in "evo_snapshot_tests/populated_v3_golden_value": check GetEvoSnapshotHash(SyntheticSnapshot()).ToString() == "bb1985a651ed3110218a3c8d65d77c85facdc544d6b9203f0815d5785c1f01ff" has failed [5b5d496a66d93775a6a6d1badf2ea2d5bbb25b58031fe0dd2c3c670674c6908d != bb1985a651ed3110218a3c8d65d77c85facdc544d6b9203f0815d5785c1f01ff]
```
https://github.com/dashpay/dash/actions/runs/35392420248/job/105760163395#step:18:836

The `populated_v3_golden_value` case hard-codes the expected `GetEvoSnapshotHash()` output. That constant was computed on the branch of PR #7592, which forked from 9efe761d4b and therefore predates PR #7437 (Decentralized Masternode Shares DIP), merged in between.

#7437 extended the `CDeterministicMNState` serializer for ExtAddr-version entries:

    if (obj.nVersion >= ProTxVersion::ExtAddr) {
        READWRITE(obj.payouts, obj.shares, obj.nEarlyPeriodBlocks, obj.nEarlyPenalty);

`SyntheticSnapshot()` builds its list via `MNList()`, which includes an ExtAddr entry, so the serialized snapshot grew and the hash changed. Both PRs were green on their own bases; develop was not.

Only the constant is stale: the codec itself is self-consistent, as the roundtrip, canonicality and representation-independence cases in the same file all pass. Including the new fields in the snapshot hash is correct, since they are part of consensus masternode state, and the decoder needs no adaptation for shared masternodes because it reconstructs the list through `CDeterministicMNList::AddMN()`, which #7437 already taught to register per-share owner keys.

## What was done?

Update the constant

## How Has This Been Tested?

Run test

## Breaking Changes

n/a

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by thepastaclaw** [comment]
⚠️ DEGRADED — Queued for automated review — 25th in line, estimated start in ~5 h (commit 216f15a8)
_Estimated review time once started: ~25 min (two-phase automated review; median of recent runs)._
_The primary review models are currently out of quota; this review will run on stand-in models and be marked as degraded._

- [ ] **Request priority review** — click to move this review to the front of the queue.

**Comment by PastaPastaPasta** [comment]
https://github.com/dashpay/dash/pull/7698 :)
