### PR TITLE
backport: bitcoin/bitcoin#30131, #23258, #30504 - fix bild for Ubuntu 24.10 + clang

### PR DESCRIPTION
**Pull request by knst**
## Issue being fixed or feature implemented
It fixes build with clang 19.1.1 (default clang version on Ubuntu 24.10)

## What was done?
Backport 30131, 30504 to fix compilation error and warning; 23258 to reduce conflicts.
See commit messages for details

## How Has This Been Tested?
Build and succeed
```
CC=clang CXX=clang++ ./configure --prefix=$(pwd)/depends/x86_64-pc-linux-gnu --enable-suppress-external-warnings   --enable-debug  --enable-stacktraces --enable-werror --enable-crash-hooks --enable-maintainer-mode --enable-multiprocess
```

## Breaking Changes
N/A

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by PastaPastaPasta — APPROVED** [review]
utACK e994691e2d5ed53c071218814aac25b5336b490c
