### PR TITLE
chore: consolidate oft-repeated type definitions to `llmq/types.h`

### PR DESCRIPTION
**Pull request by kwvg**
## Additional Information

* Depends on https://github.com/dashpay/dash/pull/6828

## Breaking Changes

None expected.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation
- [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

### CODE REVIEW

**Comment by kwvg** [comment]
@coderabbitai review

**Review by UdjinM6 — DISMISSED** [review]
utACK 1afa76ec387ff327faf9d9ad8d6289e58d53a68e

File: src/evo/deterministicmns.h [hunk 1]
```diff
@@ -11,13 +11,15 @@
...
 #include <consensus/params.h>
 #include <crypto/common.h>
-#include <evo/dmn_types.h>
-#include <evo/providertx.h>
-#include <gsl/pointers.h>
 #include <saltedhasher.h>
 #include <scheduler.h>
 #include <sync.h>
 
+#include <evo/dmn_types.h>
```
Comment (knst) [inline src/evo/deterministicmns.h]: It's not backported file; if you want to group "evo" headers they should be on the top. Because general idea to go from the most specifict headers to more less (general, system) specific headers.

Orders should be:

1. header for this cpp file (such as deterministicsitmns.h for determinististicmns.cpp)
2. headers of the same module. For evo/deterministicticmns.h it's evo/*
3. common project headers (such as clienversion.h, sync.h, etc)
4. project specific libraries, such as gsl/ or immer/
5. cpp headers & system headers (such as `atomic` or `sys/file.h`)

This general rule help to maintain standalone (self-sufficient) headers.

For this particular file, it means that `evo/dmn_types.h` *should* include "sync.h" if it uses it; otherwise it will get compilation error. Now this file is included _after_ sync.h and it means it will indirectly uses all defines, types, namespaces from sync.h.

So, maintaining this order from "less general" to "more general" helps "for free" prevent missing includes in each header.

of course, there's an exception for a backported code; when dash specific includes  _usually_ are put after bitcoin's includes; but that's a bad practice that is used only to make backports from bitcoin easier.

**Review by knst — CHANGES_REQUESTED** [review]
_removed_ (sent too early)

UPD: consider https://github.com/dashpay/dash/pull/6851

motivation: this helper is not _evo_ specific, but could be used all over codebase.
No extra header is needed, saltedhasher.h fits good enough

File: src/evo/deterministicmns.h (hunk 1 above)
Comment (kwvg) [reply src/evo/deterministicmns.h]: Resolved in latest push

File: src/llmq/utils.cpp [hunk 2]
```diff
@@ -4,30 +4,26 @@
...
 #include <llmq/utils.h>
 
+#include <bls/bls.h>
+#include <evo/deterministicmns.h>
 #include <llmq/options.h>
 #include <llmq/snapshot.h>
+#include <llmq/types.h>
+#include <masternode/meta.h>
+#include <util/irange.h>
+#include <util/ranges.h>
```
Comment (knst) [inline src/llmq/utils.cpp:14]: nit: util should not be on the top?

**Review by knst — APPROVED** [review]
LGTM e7d35e6db2d35dd7621ad3978271ce097a2bc457

File: src/llmq/utils.cpp (hunk 2 above)
Comment (kwvg) [reply src/llmq/utils.cpp:14]: Both are Dash-specific headers, `util/irange.h` was introduced in [dash#4788](https://github.com/dashpay/dash/pull/4788) and `util/ranges.h` was introduced in [dash#4622](https://github.com/dashpay/dash/pull/4622).
